
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: funny_video_dev
test:
  <<: *default
  database: funny_video_test

production:
  <<: *default
  database: funny_video_prod
